name: asunder Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build
      run: |
        wget https://raw.githubusercontent.com/ivan-hc/Database-of-pkg2appimaged-packages/main/asunder
        chmod a+x ./asunder
        ./asunder
        mkdir dist
        VERSION=$(curl -s https://packages.debian.org/oldstable/asunder | grep "Package: asunder " | cut -c 23- | rev | cut -c 2- | rev)
        mv *AppImage dist/Asunder-$VERSION-x86_64.AppImage
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: asunder-x86_64.AppImage
        path: 'dist'
        
  release:
      needs: [build]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: asunder-x86_64.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: asunder
            automatic_release_tag: asunder
            prerelease: false
            draft: false
            files: |
              asunder-x86_64.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}
