name: baobab3 Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build
      run: |
        sudo apt update && sudo apt install libfuse2
        wget https://raw.githubusercontent.com/ivan-hc/Database-of-pkg2appimaged-packages/main/baobab3
        chmod a+x ./baobab3
        ./baobab3
        mkdir dist
        mv *AppImage dist/
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: baobab3-x86_64.AppImage
        path: 'dist'
        
  release:
      needs: [build]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: baobab3-x86_64.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: baobab3
            automatic_release_tag: baobab3
            prerelease: false
            draft: false
            files: |
              baobab3-x86_64.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}
