name: billard-gl Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build
      run: |
        wget https://raw.githubusercontent.com/ivan-hc/Database-of-pkg2appimaged-packages/main/billard-gl
        chmod a+x ./billard-gl
        ./billard-gl
        mkdir dist
        mv *AppImage dist/
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: billard-gl-x86_64.AppImage
        path: 'dist'
        
  release:
      needs: [build]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: billard-gl-x86_64.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: billard-gl
            automatic_release_tag: billard-gl
            prerelease: false
            draft: false
            files: |
              billard-gl-x86_64.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}
