
name: CI
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Asunder
      run: |
        wget https://raw.githubusercontent.com/ivan-hc/Database-of-pkg2appimaged-packages/main/asunder
        chmod a+x ./asunder
        ./asunder
        mkdir dist
        mv *AppImage dist/
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Asunder-x86_64.AppImage
        path: 'dist'

    - name: Audacious
      run: |
        wget https://raw.githubusercontent.com/ivan-hc/Database-of-pkg2appimaged-packages/main/audacious
        chmod a+x ./audacious
        ./audacious
        mkdir dist
        mv *AppImage dist/
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Audacious-x86_64.AppImage
        path: 'dist'
        

  release:
      needs: [build]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Asunder build
            automatic_release_tag: asunder
            prerelease: false
            draft: false
            files: |
              Asunder-x86_64.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            
        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Audacious build
            automatic_release_tag: audacious
            prerelease: false
            draft: false
            files: |
              Audacious-x86_64.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            
