name: extremetuxracer Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build
      run: |
        sudo apt update && sudo apt install libfuse2
        wget https://raw.githubusercontent.com/ivan-hc/Database-of-pkg2appimaged-packages/main/extremetuxracer
        chmod a+x ./extremetuxracer
        ./extremetuxracer
        mkdir dist
        VERSION=$(curl -s https://packages.debian.org/stable/extremetuxracer | grep "Package: extremetuxracer " | cut -c 31- | rev | cut -c 2- | rev)
        mv *AppImage dist/Extreme_Tux_Racer-$VERSION-x86_64.AppImage
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: extremetuxracer-x86_64.AppImage
        path: 'dist'
        
  release:
      needs: [build]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: extremetuxracer-x86_64.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: extremetuxracer
            automatic_release_tag: extremetuxracer
            prerelease: false
            draft: false
            files: |
              extremetuxracer-x86_64.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}
