name: kwave Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build
      run: |
        APP=kwave
        sudo apt update && sudo apt install libfuse2
        wget https://raw.githubusercontent.com/ivan-hc/Database-of-pkg2appimaged-packages/main/$APP
        chmod a+x ./$APP
        sudo ./$APP
        mkdir dist
        VERSION=$(curl -s https://packages.debian.org/stable/$APP | grep "Package: $APP " | cut -c 21- | rev | cut -c 2- | rev)
        mv ./*.AppImage dist/Kwave_Sound_Editor-$VERSION-x86_64.AppImage
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: kwave-x86_64.AppImage
        path: 'dist'
        
  release:
      needs: [build]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: kwave-x86_64.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: kwave
            automatic_release_tag: kwave
            prerelease: false
            draft: false
            files: |
              kwave-x86_64.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}
